// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5hWP3XAvf1dim4ZQLY5NlBruA1H0mAb0',
    appId: '1:996411830424:web:ae6240d09cd0ef3196e0ed',
    messagingSenderId: '996411830424',
    projectId: 'insta-36023',
    authDomain: 'insta-36023.firebaseapp.com',
    storageBucket: 'insta-36023.firebasestorage.app',
    measurementId: 'G-Y96N2PHJHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk0DH0VO9tovuEKejV3VEuMp_RackvSv4',
    appId: '1:996411830424:android:8ac116b9a32360ae96e0ed',
    messagingSenderId: '996411830424',
    projectId: 'insta-36023',
    storageBucket: 'insta-36023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2eQI0WkTCvckNlCsl2dSmJzm71cnGWO4',
    appId: '1:996411830424:ios:e028756517e22b3c96e0ed',
    messagingSenderId: '996411830424',
    projectId: 'insta-36023',
    storageBucket: 'insta-36023.firebasestorage.app',
    iosBundleId: 'com.example.myUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2eQI0WkTCvckNlCsl2dSmJzm71cnGWO4',
    appId: '1:996411830424:ios:e028756517e22b3c96e0ed',
    messagingSenderId: '996411830424',
    projectId: 'insta-36023',
    storageBucket: 'insta-36023.firebasestorage.app',
    iosBundleId: 'com.example.myUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5hWP3XAvf1dim4ZQLY5NlBruA1H0mAb0',
    appId: '1:996411830424:web:6309f213d1eba22796e0ed',
    messagingSenderId: '996411830424',
    projectId: 'insta-36023',
    authDomain: 'insta-36023.firebaseapp.com',
    storageBucket: 'insta-36023.firebasestorage.app',
    measurementId: 'G-VQLSJ1Y1CX',
  );
}
